version: 2.1

jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore cached dependencies
          keys:
            - chrome-remote-interface-haskell--{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update dependencies
          command: make setup
      - run:
          name: Build the project
          command: make build
      - save_cache:
          name: Cache dependencies
          key: chrome-remote-interface-haskell--{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
          paths:
            - ".stack"
            - ".stack-work"
