version: 2.1

jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore cached dependencies
          keys:
            - chrome-remote-interface-haskell--{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}-v1
      - run:
          name: Resolve/Update dependencies
          command: make setup
      - run:
          name: Build the project
          command: make build
      - save_cache:
          name: Cache dependencies
          key: chrome-remote-interface-haskell--{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}-v1
          paths:
            - ".stack"
            - ".stack-work"
            - "/root/.stack"
  doc-build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore cached dependencies
          keys:
            - chrome-remote-interface-haskell--{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}-v1
      - run:
          name: Resolve/Update dependencies
          command: make setup
      - run:
          name: Build the project documentation
          command: make build-doc
      - persist_to_workspace:
          root: docs/
          paths: .
  doc-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/
      - add_ssh_keys:
          fingerprints:
            - "d4:9d:67:ed:ea:64:65:6a:d0:f4:f5:ba:15:5f:ca:7b"
      - run:
          name: Deploy documentation
          command: "./scripts/ci/deploy-docs.sh"

workflows:
  version: 2
  build:
    jobs:
      - build
      - doc-build
      - doc-deploy:
          requires:
            - build
            - doc-build
          filters:
            branches:
              only: master
