version: 2.1

jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore cached dependencies
          keys:
            - chrome-remote-interface-haskell--{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
            - stack-lts--{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update dependencies
          command: make setup
      - run:
          name: Build the project
          command: make build
      - save_cache:
          name: Cache LTS modules
          key: stack-lts--{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
          paths:
            - "/root/.stack"
      - save_cache:
          name: Cache dependencies
          key: chrome-remote-interface-haskell--{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
          paths:
            - ".stack"
            - ".stack-work"
  doc-build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore cached dependencies
          keys:
            - chrome-remote-interface-haskell--{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
            - stack-lts--{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update dependencies
          command: make setup
      - run:
          name: Build the project documentation
          command: make build-doc
      - persist_to_workspace:
          root: docs/
          paths: .
  doc-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/
      - run:
          name: Setup git configuration
          command: |
            git config user.email "ci-build@thomascrevoisier.net"
            git config user.name "ci-build"
            git add docs/
            git commit "Update documentation"
            git push --quiet origin master

workflows:
  version: 2
  build:
    jobs:
      - build
      - doc-build
      - doc-deploy:
          requires:
            - build
            - doc-build
          filters:
            branches:
              only: master
